spring.application.name=bolao-copa

# PostgreSQL
# O Spring usará a URL completa se fornecida, ou montará uma se as variáveis individuais existirem
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bolao}}
spring.datasource.username=${DB_USERNAME:bolao}
spring.datasource.password=${DB_PASSWORD:bolao}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Permite que o Render controle a porta
server.port=${PORT:8080}

# Pontuacao do bolao
bolao.pontos.resultado-exato=5
bolao.pontos.vencedor=2
