spring.application.name=bolao-copa

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bolao}
spring.datasource.username=${DB_USERNAME:bolao}
spring.datasource.password=${DB_PASSWORD:bolao}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# Pontuacao do bolao
bolao.pontos.resultado-exato=5
bolao.pontos.vencedor=2
